### ISSUE TITLE
Path-weighted metrics?

### ISSUE THREAD

**Issue by Gabesarch** [OSU-NLP-Group/LLM-Planner#3]
Hi, 

Very cool work! I was wondering if you have the path-length-weighted metrics for your model and the baselines in your few-shot table? Thank you!

<img width="671" alt="image" src="https://github.com/OSU-NLP-Group/LLM-Planner/assets/2031549/c64a399a-b1ef-418a-96c7-9381b96cdc54">

**Comment by chanhee-luke** [comment]
Hi, here are PLW SR for our methods:

Goal instructions only
LLM-Planner + HLSM
Test Unseen: 3.67
Valid Unseen: 3.08

Step-by-step instructions
LLM-Planner + HLSM
Test Unseen: 3.89
Valid Unseen: 4.11

HLSM:
Test Unseen: 0.09
Valid Unseen: 0.00

FILM:
Test Unseen: 0.04
Valid Unseen: 0.00

Note that PWL SR depends significantly on your choice of the low-level planner, rather than on the high-level planner (e.g. LLM-Planner).

**Comment by Gabesarch** [comment]
Thank you so much!
