### ISSUE TITLE
Hello, may I ask when all open source code is expected to be released? Thank you!

### ISSUE THREAD

**Issue by Alpha-kc** [OSU-NLP-Group/LLM-Planner#4]

**Comment by chanhee-luke** [comment]
Hi, thanks for the interest!

Sorry it's taking some time, we are packaging the release with a ground-truth low-level planner, so that you can accurately isolate the performance of the high-level planner.
We plan to release it before Thanksgiving, with more exciting updates!

In the meantime, you will be able to replicate the results for HLP ACC with the code and few-shot dataset provided.

**Comment by Alpha-kc** [comment]
Thank you very much for your reply.
